package com.dronegcs.mavlink.is.protocol.msg_metadata.enums;

import com.dronegcs.mavlink.is.units.Range;
import com.opencsv.CSVWriter;

import java.io.FileWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public enum MAV_PARAM_PLANE implements MAV_PARAM_I {

    THR_PASS_STAB(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,new Range(-100,100),false,"","Throttle passthru in stabilize"),
    THR_FAILSAFE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Disable");put(1,"Enable");}},false,"",""),
    GPS_SBAS_MODE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Disabled");put(1,"Enable");put(2,"NoChange");}},false,"",""),
    FORMAT_VERSION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,13,1,MAV_PARAM_UNIT.UNKNOWN,new Range(1,255),false,"","Eeprom format version number"),
    SYSID_SW_TYPE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Unknown"),
    SYSID_THISMAV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,new Range(1,255),false,"","MAVLink system ID of this vehicle"),
    SYSID_MYGCS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,255,1,MAV_PARAM_UNIT.UNKNOWN,new Range(1,255),false,"","Ground station MAVLink system ID"),
    SERIAL0_PROTOCOL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(1,"MAVlink1");put(2,"MAVlink2");}},false,"",""),
    SERIAL0_BAUD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,115,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"1200");put(2,"2400");put(4,"4800");put(9,"9600");put(19,"19200");put(38,"38400");put(57,"57600");put(111,"111100");put(115,"115200");put(256,"256000");put(460,"460800");put(500,"500000");put(921,"921600");put(1500,"1500000");}},false,"",""),
    SERIAL1_PROTOCOL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(1,"MAVlink1");put(2,"MAVlink2");}},false,"",""),
    SERIAL1_BAUD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,57,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"1200");put(2,"2400");put(4,"4800");put(9,"9600");put(19,"19200");put(38,"38400");put(57,"57600");put(111,"111100");put(115,"115200");put(256,"256000");put(460,"460800");put(500,"500000");put(921,"921600");put(1500,"1500000");}},false,"",""),
    SERIAL2_PROTOCOL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(1,"MAVlink1");put(2,"MAVlink2");}},false,"",""),
    SERIAL2_BAUD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,57,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"1200");put(2,"2400");put(4,"4800");put(9,"9600");put(19,"19200");put(38,"38400");put(57,"57600");put(111,"111100");put(115,"115200");put(256,"256000");put(460,"460800");put(500,"500000");put(921,"921600");put(1500,"1500000");}},false,"",""),
    SERIAL3_PROTOCOL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(1,"MAVlink1");put(2,"MAVlink2");}},false,"",""),
    SERIAL3_BAUD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,38,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"1200");put(2,"2400");put(4,"4800");put(9,"9600");put(19,"19200");put(38,"38400");put(57,"57600");put(111,"111100");put(115,"115200");put(256,"256000");put(460,"460800");put(500,"500000");put(921,"921600");put(1500,"1500000");}},false,"",""),
    SERIAL4_PROTOCOL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(1,"MAVlink1");put(2,"MAVlink2");}},false,"",""),
    SERIAL4_BAUD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,38,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"1200");put(2,"2400");put(4,"4800");put(9,"9600");put(19,"19200");put(38,"38400");put(57,"57600");put(111,"111100");put(115,"115200");put(256,"256000");put(460,"460800");put(500,"500000");put(921,"921600");put(1500,"1500000");}},false,"",""),
    AUTOTUNE_LEVEL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,6,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Autotune level"),
    TELEM_DELAY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,new Range(0,30),false,"","Telemetry startup delay"),
    GCS_PID_MASK(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,new HashMap<Number, String>(){{put(0,"Roll");put(1,"Pitch");put(2,"Yaw");put(3,"Steering");put(4,"Landing");}},false,"",""),
    KFF_RDDRMIX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.5,0.01,MAV_PARAM_UNIT.UNKNOWN,new Range(0,1),false,"","Rudder Mix"),
    KFF_THR2PTCH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,0.01,MAV_PARAM_UNIT.UNKNOWN,new Range(0,1),false,"","Throttle to Pitch Mix"),
    STAB_PITCH_DOWN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,0.01,MAV_PARAM_UNIT.UNKNOWN,new Range(0,15),false,"","Low throttle pitch down trim"),
    GLIDE_SLOPE_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,15,1,MAV_PARAM_UNIT.METER,new Range(0,1000),false,"","Glide slope minimum"),
    GLIDE_SLOPE_THR(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,new Range(0,100),false,"","Glide slope threshold"),
    STICK_MIXING(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Disabled");put(1,"FBWMixing");put(2,"DirectMixing");}},false,"",""),
    SKIP_GYRO_CAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Unknown"),
    AUTO_FBW_STEER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Disabled");put(42,"Enabled");}},false,"","Use FBWA steering in AUTO, 0:Disabled 42:Enabled"),
    TKOFF_THR_MINSPD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,0.1,MAV_PARAM_UNIT.METER_PER_SECOND,new Range(0,30),false,"","Takeoff throttle min speed"),
    TKOFF_THR_MINACC(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,0.1,MAV_PARAM_UNIT.METER_PER_SECOND_PER_SECOND,new Range(0,30),false,"","Takeoff throttle min acceleration"),
    TKOFF_THR_DELAY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.UNKNOWN,new Range(0,127),false,"","Takeoff throttle delay (MAV_PARAM_GROUP.ARDUPLANE,Increment 1 deciseconds)"),
    TKOFF_TDRAG_ELEV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","FBWA taildragger channel"),
    TKOFF_TDRAG_SPD1(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,0.1,MAV_PARAM_UNIT.METER_PER_SECOND,new Range(0,30),false,"","Takeoff tail dragger speed1"),
    TKOFF_ROTATE_SPD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,0.1,MAV_PARAM_UNIT.METER_PER_SECOND,new Range(0,30),false,"","Takeoff rotate speed"),
    TKOFF_THR_SLEW(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,new Range(-1,127),false,"","Takeoff throttle slew rate"),
    TKOFF_FLAP_PCNT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,new Range(0,100),false,"","Takeoff flap percentage"),
    FBWA_TDRAG_CHAN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","FBWA taildragger channel"),
    LEVEL_ROLL_LIMIT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.DEGREE,new Range(0,45),false,"","Level flight roll limit"),
    LAND_PITCH_CD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Landing Pitch"),
    LAND_FLARE_ALT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3,0.1,MAV_PARAM_UNIT.DEGREE,false,"","Landing flare altitude"),
    LAND_FLARE_SEC(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,0.1,MAV_PARAM_UNIT.DEGREE,false,"","Landing flare time"),
    LAND_DISARMDELAY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,20,1,MAV_PARAM_UNIT.SECOND,new Range(0,127),false,"","Landing disarm delay"),
    NAV_CONTROLLER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Default");put(1,"L1Controller");}},false,"","Navigation controller selection"),
    ALT_MIX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ALT_CTRL_ALG(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,new HashMap<Number, String>(){{put(0,"Automatic");}},false,"","Altitude control algorithm"),
    ALT_OFFSET(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.METER,new Range(-32767,32767),false,"","Altitude offset"),
    WP_RADIUS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,90,1,MAV_PARAM_UNIT.METER,new Range(1,32767),false,"","Waypoint Radius"),
    WP_MAX_RADIUS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.METER,new Range(0,32767),false,"","Waypoint Maximum Radius"),
    WP_LOITER_RAD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,60,1,MAV_PARAM_UNIT.UNKNOWN,new Range(-32767,32767),false,"","Waypoint Loiter Radius"),
    FENCE_ACTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"None");put(1,"GuidedMode");put(2,"ReportOnly");put(3,"GuidedModeThrPass");put(4,"RTL_Mode");}},false,"","Action on geofence breach"),
    FENCE_TOTAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Fence Total"),
    FENCE_CHANNEL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Fence Channel"),
    FENCE_MINALT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.METER,new Range(0,32767),false,"","Fence Minimum Altitude"),
    FENCE_MAXALT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.METER,new Range(0,32767),false,"","Fence Maximum Altitude"),
    FENCE_RETALT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.METER,new Range(0,32767),false,"","Fence Return Altitude"),
    FENCE_AUTOENABLE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"NoAutoEnable");put(1,"AutoEnable");put(2,"AutoEnableDisableFloorOnly");put(3,"EnableWhenArmed");}},false,"","Fence automatic enable"),
    FENCE_RET_RALLY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"FenceReturnPoint");put(1,"NearestRallyPoint");}},false,"","Fence Return to Rally"),
    STALL_PREVENTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Disabled");put(1,"Enabled");}},false,"","Enable stall prevention"),
    ARSPD_FBW_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,9,1,MAV_PARAM_UNIT.METER_PER_SECOND,new Range(5,100),false,"","Minimum Airspeed"),
    ARSPD_FBW_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,22,1,MAV_PARAM_UNIT.METER_PER_SECOND,new Range(5,100),false,"","Maximum Airspeed"),
    FBWB_ELEV_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"Disabled");put(1,"Enabled");}},false,"","Fly By Wire elevator reverse"),
    FBWB_CLIMB_RATE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,0.1,MAV_PARAM_UNIT.METER_PER_SECOND,new Range(1,10),false,"","Fly By Wire B altitude change rate"),
    THR_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.PERCENT,new Range(-100,100),false,"","Minimum Throttle"),
    THR_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,75,1,MAV_PARAM_UNIT.PERCENT,new Range(0,100),false,"","Maximum Throttle"),
    TKOFF_THR_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.PERCENT,new Range(0,100),false,"","Maximum Throttle for takeoff"),
    THR_SLEWRATE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,100,1,MAV_PARAM_UNIT.UNKNOWN,new Range(0,127),false,"","Throttle slew rate"),
    FLAP_SLEWRATE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,75,1,MAV_PARAM_UNIT.UNKNOWN,new Range(0,100),false,"","Flap slew rate"),
    THR_SUPP_MAN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    THR_FS_VALUE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,950,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TRIM_THROTTLE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,45,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    THROTTLE_NUDGE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_SHORT_ACTN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_SHORT_TIMEOUT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1.5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_LONG_ACTN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_LONG_TIMEOUT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_BATT_VOLTAGE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_BATT_MAH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FS_GCS_ENABL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE_CH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,8,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE1(MAV_PARAM_GROUP_PLANE.ARDUPLANE,11,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE2(MAV_PARAM_GROUP_PLANE.ARDUPLANE,11,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE3(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE4(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE5(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLTMODE6(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INITIAL_MODE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    LIM_ROLL_CD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,4500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    LIM_PITCH_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2000,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    LIM_PITCH_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-2500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ACRO_ROLL_RATE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,180,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ACRO_PITCH_RATE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,180,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ACRO_LOCKING(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GROUND_STEER_ALT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GROUND_STEER_DPS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,90,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TRIM_AUTO(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ELEVON_MIXING(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ELEVON_REVERSE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ELEVON_CH1_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ELEVON_CH2_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    VTAIL_OUTPUT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ELEVON_OUTPUT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    MIXING_GAIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RUDDER_ONLY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SYS_NUM_RESETS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,13,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    LOG_BITMASK(MAV_PARAM_GROUP_PLANE.ARDUPLANE,16254,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RST_SWITCH_CH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RST_MISSION_CH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TRIM_ARSPD_CM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1200,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SCALING_SPEED(MAV_PARAM_GROUP_PLANE.ARDUPLANE,15,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    MIN_GNDSPD_CM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TRIM_PITCH_CD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ALT_HOLD_RTL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10000,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ALT_HOLD_FBWCM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    MAG_ENABLE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLAP_IN_CHANNEL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLAPERON_OUTPUT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLAP_1_PERCNT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLAP_1_SPEED(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLAP_2_PERCNT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    FLAP_2_SPEED(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    LAND_FLAP_PERCNT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RSSI_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RSSI_RANGE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INVERTEDFLT_CH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    HIL_SERVOS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    HIL_ERR_LIMIT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RTL_AUTOLAND(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TRIM_RC_AT_START(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GND_ABS_PRESS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,50705.5625,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GND_TEMP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,25,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GND_ALT_OFFSET(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GPS_TYPE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GPS_NAVFILTER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,8,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GPS_MIN_ELEV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    GPS_GNSS_MODE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    CAM_TRIGG_TYPE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    CAM_DURATION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    CAM_SERVO_ON(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1300,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    CAM_SERVO_OFF(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    CAM_TRIGG_DIST(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARMING_REQUIRE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARMING_CHECK(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARMING_RUDDER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RELAY_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,13,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RELAY_PIN2(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RELAY_PIN3(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RELAY_PIN4(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RELAY_DEFAULT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RNGFND_LANDING(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC1_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC1_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC1_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC1_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC1_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,30,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC2_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC2_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC2_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC2_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC2_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,30,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC3_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC3_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC3_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC3_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC3_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,30,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC4_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC4_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC4_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC4_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC4_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,30,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC5_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC5_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC5_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC5_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC5_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC5_FUNCTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC6_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC6_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC6_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC6_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC6_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC6_FUNCTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC7_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC7_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC7_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC7_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC7_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC7_FUNCTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC8_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC8_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC8_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC8_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC8_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC8_FUNCTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC10_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC10_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC10_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC10_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC10_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC10_FUNCTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC11_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1100,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC11_TRIM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC11_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1900,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC11_REV(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC11_DZ(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RC11_FUNCTION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_TCONST(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_P(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.400000005960465,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_D(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.0199999995529652,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_I(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.0399999991059303,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_RMAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_IMAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3000,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RLL2SRV_FF(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_TCONST(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_P(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.400000005960465,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_D(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.0199999995529652,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_I(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.0399999991059303,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_RMAX_UP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_RMAX_DN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_RLL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_IMAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3000,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    PTCH2SRV_FF(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    YAW2SRV_SLIP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    YAW2SRV_INT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    YAW2SRV_DAMP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    YAW2SRV_RLL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    YAW2SRV_IMAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_TCONST(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.75,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_P(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1.79999995231628,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_I(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.200000002980232,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_D(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.00499999988824129,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_IMAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1500,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_MINSPD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    STEER2SRV_FF(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_OFS_X(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_OFS_Y(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_OFS_Z(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_LEARN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_USE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_AUTODEC(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_MOTCT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_MOT_X(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_MOT_Y(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_MOT_Z(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_ORIENT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_EXTERNAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SCHED_DEBUG(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RCMAP_ROLL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RCMAP_PITCH(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RCMAP_THROTTLE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RCMAP_YAW(MAV_PARAM_GROUP_PLANE.ARDUPLANE,4,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_RAW_SENS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_EXT_STAT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_RC_CHAN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_RAW_CTRL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_POSITION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_EXTRA1(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_EXTRA2(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_EXTRA3(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR0_PARAMS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_RAW_SENS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_EXT_STAT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_RC_CHAN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_RAW_CTRL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_POSITION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_EXTRA1(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_EXTRA2(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_EXTRA3(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    SR1_PARAMS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_PRODUCT_ID(MAV_PARAM_GROUP_PLANE.ARDUPLANE,88,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_GYROFFS_X(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.000180917340912856,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_GYROFFS_Y(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-0.0767195895314217,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_GYROFFS_Z(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.0333446636795998,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCSCAL_X(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCSCAL_Y(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCSCAL_Z(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCOFFS_X(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCOFFS_Y(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCOFFS_Z(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_GYRO_FILTER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,20,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_ACCEL_FILTER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,20,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    INS_USE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_GPS_GAIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_GPS_USE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_YAW_P(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.200000002980232,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_RP_P(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.200000002980232,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_WIND_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_TRIM_X(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_TRIM_Y(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_TRIM_Z(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_ORIENTATION(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_COMP_BETA(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.100000001490116,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    AHRS_GPS_MINSATS(MAV_PARAM_GROUP_PLANE.ARDUPLANE,6,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_ENABLE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_USE(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_OFFSET(MAV_PARAM_GROUP_PLANE.ARDUPLANE,860.682922363281,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_RATIO(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1.99360001087189,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_AUTOCAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_TUBE_ORDER(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    ARSPD_SKIP_CAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    NAVL1_PERIOD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,20,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    NAVL1_DAMPING(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.75,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_CLMB_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_SINK_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_TIME_CONST(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_THR_DAMP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_INTEG_GAIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.100000001490116,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_VERT_ACC(MAV_PARAM_GROUP_PLANE.ARDUPLANE,7,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_HGT_OMEGA(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_SPD_OMEGA(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_RLL2THR(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_SPDWEIGHT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_PTCH_DAMP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_SINK_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_ARSPD(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_THR(MAV_PARAM_GROUP_PLANE.ARDUPLANE,-1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_SPDWGT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,1,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_PITCH_MAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_PITCH_MIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_SINK(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.25,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_TCONST(MAV_PARAM_GROUP_PLANE.ARDUPLANE,2,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_DAMP(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    TECS_LAND_PMAX(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_MONITOR(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_VOLT_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,13,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_CURR_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,12,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_VOLT_MULT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10.1000003814697,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_AMP_PERVOLT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,17,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_AMP_OFFSET(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT_CAPACITY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3300,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_MONITOR(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_VOLT_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,13,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_CURR_PIN(MAV_PARAM_GROUP_PLANE.ARDUPLANE,12,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_VOLT_MULT(MAV_PARAM_GROUP_PLANE.ARDUPLANE,10.1000003814697,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_AMP_PERVOL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,17,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_AMP_OFFSET(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BATT2_CAPACITY(MAV_PARAM_GROUP_PLANE.ARDUPLANE,3300,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    BRD_SERIAL_NUM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    MIS_TOTAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","The number of mission mission items that has been loaded by the ground station. Do not change this manually."),
    MIS_RESTART(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.FLAGS,new HashMap<Number, String>(){{put(0,"ResumeMission");put(1,"RestartMission");}},false,"","Not Yet"),
    RALLY_TOTAL(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RALLY_LIMIT_KM(MAV_PARAM_GROUP_PLANE.ARDUPLANE,5,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    RALLY_INCL_HOME(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0,1,MAV_PARAM_UNIT.UNKNOWN,false,"","Not Yet"),
    COMPASS_DEC(MAV_PARAM_GROUP_PLANE.ARDUPLANE,0.0694443434476852,1,MAV_PARAM_UNIT.RADIANS,new Range(-3.142,3.142),false,"","An angle to compensate between the true north and magnetic north"),

    ;

    private final Number defaultValue;
    private final Number increment;
    private final MAV_PARAM_UNIT unit;
    private final Range range;
    private final boolean readOnly;
    private final String title;
    private final String description;
    private final Map<Number, String> options;
    private final MAV_PARAM_GROUP_I group;

    MAV_PARAM_PLANE(MAV_PARAM_GROUP_I group, Number defaultValue, int increment, MAV_PARAM_UNIT unit, Map<Number, String> options, boolean readOnly, String title, String description) {
        this.group = group;
        this.defaultValue = defaultValue;
        this.increment = increment;
        this.unit = MAV_PARAM_UNIT.FLAGS;
        this.options = options;
        this.range = null;
        this.readOnly = readOnly;
        this.title = title;
        this.description = description;
    }

    MAV_PARAM_PLANE(MAV_PARAM_GROUP_I group, Number defaultValue, Number increment, MAV_PARAM_UNIT unit, Range range, boolean readOnly, String title, String description) {
        this.group = group;
        this.defaultValue = defaultValue;
        this.increment = increment;
        this.unit = unit;
        this.options = null;
        this.range = range;
        this.readOnly = readOnly;
        this.title = title;
        this.description = description;
    }

    MAV_PARAM_PLANE(MAV_PARAM_GROUP_I group, Number defaultValue, Number increment, MAV_PARAM_UNIT unit, boolean readOnly, String title, String description) {
        this.group = group;
        this.defaultValue = defaultValue;
        this.increment = increment;
        this.unit = unit;
        this.options = null;
        this.range = null;
        this.readOnly = readOnly;
        this.title = title;
        this.description = description;
    }

    @Override
    public String toString() {

        return "MAV_PARAMETERS_LIST{" +
                "name=" + this.name() +
                ", defaultValue=" + defaultValue +
                ", increment=" + increment +
                ", unit=" + unit +
                ", readOnly=" + readOnly +
                ", title='" + title + '\'' +
                '}';
    }

    @Override
    public MAV_PARAM_GROUP_I getGroup() {
        return group;
    }

    @Override
    public String getName() {
        return this.name();
    }

    @Override
    public Number getDefaultValue() {
        return defaultValue;
    }

    @Override
    public Number getIncrement() {
        return increment;
    }

    @Override
    public MAV_PARAM_UNIT getUnit() {
        return unit;
    }

    @Override
    public Range getRange() {
        return range;
    }

    @Override
    public Map<Number, String> getOptions() {
        return options;
    }

    @Override
    public boolean isReadOnly() {
        return readOnly;
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public String getDescription() {
        return description;
    }
}
